---

- name: Check if /var/lib/docker is located on separate volume
  shell: "lsblk --json | jq '.blockdevices | .[] | select(.children != null) | .children | .[] | select(.mountpoint == \"/var/lib/docker\") | .name'"
  args:
    executable: /bin/bash
  register: volume

- include: btrfs.yml
  when: 'volume.stdout_lines | length == 0 and docker.volume_fs == "btrfs"'

- include: zfs.yml
  when: 'volume.stdout_lines | length == 0 and docker.volume_fs == "zfs"'
