---

- name: Check if /var/lib/docker is located on separate volume
  shell: "lsblk --json | jq '.blockdevices | .[] | select(.children != null) | .children | .[] | select(.mountpoint == \"/var/lib/docker\") | .name'"
  args:
    executable: /bin/bash
  register: volume

- include: volume-docker.yml
  when: 'volume is defined and volume.stdout_lines | length == 0'
