---

- name: Install crictl
  unarchive:
    src: "https://github.com/kubernetes-incubator/cri-tools/releases/download/v{{ cri.ctl_version }}/crictl-v{{cri.ctl_version }}-linux-amd64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    owner: root
    group: root
  become: yes

- name: Install k8s tools
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s.version }}/bin/linux/amd64/{{ item }}"
    dest: "/usr/local/bin"
    mode: 0755
  with_items:
    - kubeadm
    - kubelet
    - kubectl
  become: yes

- name: Install kubelet service configuration
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ k8s.version }}/build/debs/kubelet.service"
    dest: "/etc/systemd/system/kubelet.service"
  become: yes

- name: Patch kubelet service configuration
  replace:
    path: /etc/systemd/system/kubelet.service
    regexp: /usr/bin
    replace: /usr/local/bin
  become: yes

- name: Create directories
  file:
    path: "/etc/systemd/system/kubelet.service.d"
    state: directory
  become: yes

- name: Install kubeadm configuration for kubelet
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ k8s.version }}/build/debs/10-kubeadm.conf"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
  become: yes

- name: Patch kubeadm configuration for kubelet
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: /usr/bin
    replace: /usr/local/bin
  become: yes

- name: Configure service
  systemd:
    name: kubelet
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes

- name: Install prerequisites
  apt:
    name: "{{ k8s.prerequisites }}"
  become: yes

- name: Load modules
  modprobe:
    name: "{{ item }}"
  become: yes
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
    - br_netfilter

- name: Setting sysctl
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
  become: yes

- name: Setting sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
  become: yes

- name: Get swap configuration
  shell: "swapon --noheadings | cut -d' ' -f1"
  become: yes
  register: swap

- name: Disable swap
  shell: "swapoff {{ swap.stdout_lines.0 }}"
  become: yes
  when: swap.stdout_lines | length > 0
