---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/cni/bin
    - /etc/cni/net.d
  become: yes

- name: Install CNI
  unarchive:
    src: "https://github.com/containernetworking/cni/releases/download/v{{ cni.version }}/cni-amd64-v{{ cni.version }}.tgz"
    dest: "/opt/cni/bin"
    remote_src: yes
  become: yes
