---

- debug: msg="BEGIN role cni"

- include: binaries.yml

- include: plugins.yml
  when: cni.components is defined and 'plugins' in cni.components

- include: bridge.yml
  when: cni.config is defined and 'bridge' in cni.config

- debug: msg="END role cni"
