---

- name: Prepare DNS
  hosts: first_controller
  vars_files:
    - vars/global.yml
    - vars/cloudflare/vars.yml
    - vars/cloudflare/vault.yml
  tasks:
    - name: Clear DNS records for load balancer
      cloudflare_dns:
        zone: "{{ dns.zone }}"
        record: "{{ dns.record }}"
        type: A
        state: absent
        account_email: "{{ cloudflare.email }}"
        account_api_token: "{{ cloudflare.token }}"
    - name: Create DNS record for first node
      cloudflare_dns:
        zone: "{{ dns.zone }}"
        record: "{{ dns.record }}"
        type: A
        value: "{{ ansible_default_ipv4.address }}"
        account_email: "{{ cloudflare.email }}"
        account_api_token: "{{ cloudflare.token }}"
  tags:
    - k8s-cluster-init

- name: Initialize cluster
  hosts: first_controller
  vars_files:
    - vars/global.yml
  roles:
    - role: k8s-cluster-init
    - role: k8s-cni-weave
  tags:
    - k8s-cluster-init

- name: Deploy additional masters
  hosts: additional_controllers
  serial: 1
  vars_files:
    - vars/global.yml
    - vars/cloudflare/vars.yml
    - vars/cloudflare/vault.yml
  vars:
    first_controller: "{{ groups['first_controller'][0] }}"
  roles:
    - role: k8s-controller-join
  tasks:
    - name: Add DNS record for load balancer
      cloudflare_dns:
        zone: "{{ dns.zone }}"
        record: "{{ dns.record }}"
        type: A
        value: "{{ ansible_default_ipv4.address }}"
        account_email: "{{ cloudflare.email }}"
        account_api_token: "{{ cloudflare.token }}"
  tags:
    - k8s-controller-join

- name: Configure control planes
  hosts: controller
  roles:
    - role: k8s-controller-finish
    - role: k8s-controller-all-nodeports
  tags:
    - k8s-controller-all-nodeports

- name: Deploy workers
  hosts: worker
  vars_files:
    - vars/global.yml
  vars:
    controller: "{{ groups['first_controller'][0] }}"
  roles:
    - role: k8s-worker-join
  tags:
    - k8s-worker-join
