---

- name: Remove nodes
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/hcloud/vars.yml
    - vars/hcloud/vault.yml
  tasks:
    - hcloud_server:
        name:
          - master1
          - master2
          - master3
          - worker1
          - worker2
        state: absent
        token: "{{ hcloud.token }}"
    - file:
        path: "~/.ssh/config.d/hcloud_{{ item.name }}"
        state: absent
      with_items: "{{ nodes.servers }}"
