---

#- name: Create SSH key

- name: Initialize cluster
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Provision workers
      hcloud_server:
        name:
          - worker1
          - worker2
        image: ubuntu-18.04
        server_type: cx21
        location: fsn1
        ssh_keys:
          - 209622
        token: "{{ hcloud.token }}"
      register: workers
    - name: Store workers in inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.public_ipv4 }}"
        ansible_user: root
        ansible_ssh_private_key: "~/id_rsa_hetzner"
        groups:
          - hcloud
      with_items: "{{ workers.servers }}"

- name: Continue
  hosts: hcloud
  tasks:
    - name: Test
      command: hostname
