---

- name: Inventory
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/global.yml
  tasks:
    - set_fact:
        controller_list: "{{ controller_list | default([]) }} + [ '{{ controller.prefix }}{{ \"%02x\" | format(item) }}' ]"
      loop: "{{ range(1, controller.count + 1, 1) | list }}"
    - set_fact:
        worker_list: "{{ worker_list | default([]) }} + [ '{{ worker.prefix}}{{ \"%02x\" | format(item) }}' ]"
      loop: "{{ range(1, worker.count + 1, 1) | list }}"
    - set_fact:
        vm_list: "{{ controller_list + worker_list }}"
    - name: Create group for controller
      add_host:
        name: "{{ item }}"
        groups:
          - controller
      with_items: "{{ controller_list }}"
    - name: Create group for first controller
      add_host:
        name: "{{ controller_list | sort | first }}"
        groups:
          - first_controller
    - name: Create group for additional controller
      add_host:
        name: "{{ item }}"
        groups:
          - additional_controllers
      with_items: "{{ controller_list | difference(groups['first_controller']) }}"
    - name: Create group for worker
      add_host:
        name: "{{ item }}"
        groups:
          - k8s
          - worker
        ansible_user: "{{ ssh_user }}"
        ansible_ssh_private_key_file: "{{ ssh_private_key }}"
      with_items: "{{ worker_list }}"
