---

- name: Prepare inventory
  hosts: localhost
  gather_facts: no
  vars:
    master_pattern: "^master[0-9]+$"
    worker_pattern: "^worker[0-9]+$"
  tasks:
    - name: Create group for masters
      add_host:
        name: "{{ item }}"
        groups:
          - k8s
          - controller
        ansible_user: root
        ansible_ssh_private_key_file: "~/id_rsa_hetzner"
      with_items: "{{ groups['all'] | select('match', master_pattern) | list }}"
    - name: Create group for first master
      add_host:
        name: "{{ groups['controller'] | first() }}"
        groups:
          - first_controller
    - name: Create group for additional masters
      add_host:
        name: "{{ item }}"
        groups:
          - additional_controllers
      with_items: "{{ groups['controller'] | difference(groups['first_controller']) }}"
    - name: Create group for masters
      add_host:
        name: "{{ item }}"
        groups:
          - k8s
          - worker
        ansible_user: root
        ansible_ssh_private_key_file: "~/id_rsa_hetzner"
      with_items: "{{ groups['all'] | select('match', worker_pattern) | list }}"

- name: Prepare all nodes
  hosts: k8s
  roles:
    - role: cni
    - role: containerd
    - role: k8s-node-prepare
    - role: k8s-cri-containerd
  tags:
    - k8s-node-prepare

- name: Initialize cluster
  hosts: first_controller
  roles:
    - role: k8s-cluster-init
    - role: k8s-cni-weave
  tags:
    - k8s-cluster-init

- name: Deploy additional masters
  hosts: additional_controllers
  serial: 1
  vars:
    first_controller: "{{ groups['cluster_init'][0] }}"
  roles:
    - role: k8s-controller-join
  tags:
    - k8s-controller-join

- name: Configure control planes
  hosts: controller
  roles:
    - role: k8s-controller-finish
    - role: k8s-controller-all-nodeports
  tags:
    - k8s-controller-all-nodeports

- name: Deploy workers
  hosts: worker
  roles:
    - role: k8s-worker-join
  tags:
    - k8s-worker-join
