---

- import_playbook: prepare.yml

- import_playbook: inventory.yml

- import_playbook: provision_hcloud.yml
  when: 'provisioner | default() == "hcloud"'

- import_playbook: provision_vsphere.yml
  when: 'provisioner | default() == "vsphere"'

- name: Prepare all nodes
  hosts: k8s
  vars_files:
    - vars/global.yml
  roles:
    - role: volume-docker
      when: 'use_volumes'
    - role: docker
    - role: k8s-node-prepare
  tags:
    - k8s-node-prepare

- import_playbook: cluster.yml
