---

- name: Initialize cluster
  hosts: controlplane_init
  roles: 
    - role: docker
      components: [engine]
      vars:
        docker:
          version: "18.06.*"
    - role: k8s
      components: [tools, controlplane_init]

- name: Deploy additional masters
  hosts: controlplane_join
  roles:
    - role: docker
      components: [engine]
      vars:
        docker:
          version: "18.06.*"
    - role: k8s
      components: [tools, controlplane]

#- name: Deploy workers
#  hosts: worker
#  roles:
#    - role: containerd
#    - role: k8s
#      components: [tools, worker]
#      runtime: containerd
