---

- name: Initialize cluster
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Provision workers
      hcloud_server:
        name:
          - master1
          - master2
        image: ubuntu-18.04
        server_type: cx21
        location: fsn1
        ssh_keys:
          - 209622
        token: "{{ hcloud.token }}"
      register: workers
    - name: Store workers in inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.public_ipv4 }}"
        ansible_user: root
        ansible_ssh_private_key_file: "~/id_rsa_hetzner"
        groups:
          - hcloud
      with_items: "{{ workers.servers }}"

- name: Prepare nodes for Ansible
  hosts: all
  gather_facts: no
  tasks:
    - name: Install updates
      raw: "apt-get update && apt-get -y upgrade"
    - name: Install Python
      raw: "apt-get -y install python-pip"

- name: Initialize cluster
  hosts: all
  roles: 
    - role: k8s
      k8s:
        components: [tools]
        runtime: docker

- name: Initialize cluster
  hosts: controlplane_init
  roles: 
    - role: k8s
      k8s:
        components: [controlplane_init]
        runtime: docker
        network: weave

- name: Deploy additional masters
  hosts: controlplane_join
  roles:
    - role: k8s
      k8s:
        components: [controlplane]
        runtime: docker

#- name: Configure control planes
#  hosts: controlplane
#  roles:
#    - role: k8s
#      feature: [all_nodeports]

#- name: Deploy workers
#  hosts: worker
#  roles:
#    - role: containerd
#    - role: k8s
#      components: [tools, worker]
#      runtime: containerd
