---

- name: Prepare nodes for Ansible
  hosts: all
  gather_facts: no
  tasks:
    - name: Install updates
      raw: "apt-get update && apt-get -y upgrade"
    - name: Install Python
      raw: "apt-get -y install python-pip"

- name: Initialize cluster
  hosts: controlplane_init
  roles: 
    - role: k8s
      k8s:
        components: [tools, controlplane_init]
        runtime: docker
        network: weave

- name: Deploy additional masters
  hosts: controlplane_join
  roles:
    - role: k8s
      k8s:
        components: [tools, controlplane]
        runtime: docker

#- name: Configure control planes
#  hosts: controlplane
#  roles:
#    - role: k8s
#      feature: [all_nodeports]

#- name: Deploy workers
#  hosts: worker
#  roles:
#    - role: containerd
#    - role: k8s
#      components: [tools, worker]
#      runtime: containerd
