---

- name: Install HTTPS transport
  package:
    name: "{{ item }}"
  with_items:
  - apt-transport-https
  - ca-certificates
  become: yes

- name: Add key
  when: key_url is defined
  apt_key:
    url: "{{ key_url }}"
  become: yes

- name: Add repository
  when: apt_repo is defined
  apt_repository:
    repo: "{{ apt_repo }}"
    filename: "{{ name }}"
  become: yes

- name: Update package list
  apt:
    update: yes
  become: yes