---

- debug: var=k8s.version

- include: tools.yml
  when: components is defined and 'tools' in components

- include: runtime_containerd.yml
  when: runtime is defined and runtime == 'containerd'

- include: prepare.yml
  when: components is defined and ( 'controlplane_init' in components or 'controlplane' in components or 'worker' in components )

- name: Check for running control plane
  shell: "netstat -tulpan | grep LISTEN | grep :::6443"
  ignore_errors: yes
  register: port_6443

- include: controlplane_init.yml
  when: components is defined and 'controlplane_init' in components and port_6443.failed

- include: network_weave.yml
  when: components is defined and 'controlplane_init' in components and port_6443.failed and network is defined and network == 'weave'

- include: controlplane.yml
  when: components is defined and 'controlplane' in components and port_6443.failed

- include: feature_nodeports.yml
  when: feature is defined and 'all_nodeports' in feature

- include: feature_untaint.yml
  when: feature is defined and 'untaint' in feature

- include: worker.yml
  when: components is defined and 'worker' in components
