---

- debug: msg="BEGIN Role k8s"

- include: tools.yml
  when: '"tools" in k8s.components'

- include: runtime_containerd.yml
  when: 'k8s.runtime == "containerd"'

- include: prepare.yml
  when: '"controlplane_init" in k8s.components or "controlplane" in k8s.components or "worker" in k8s.components'

- name: Check for running control plane
  shell: "netstat -tulpan | grep LISTEN | grep :::6443"
  ignore_errors: yes
  register: port_6443

- include: controlplane_init.yml
  when: '"controlplane_init" in k8s.components and port_6443 is defined and port_6443.failed'

- include: network_weave.yml
  when: '"controlplane_init" in k8s.components and port_6443 is defined and port_6443.failed and k8s.network == "weave"'

- include: controlplane.yml
  when: '"controlplane" in k8s.components and port_6443.failed'

- include: feature_nodeports.yml
  when: '"all_nodeports" in k8s.features'

- include: feature_untaint.yml
  when: '"untaint" in k8s.features'

- include: worker.yml
  when: '"worker"in k8s.components'

- debug: msg="END role k8s"
