---

- debug: var=k8s.version

- include: tools.yml
  when: components is defined and 'tools' in components

- include: containerd.yml
  when: runtime is defined and runtime == 'containerd'

- include: prepare.yml
  when: components is defined and ( 'controlplane_init' in components or 'controlplane' in components or 'worker' in components )

- include: controlplane_init.yml
  when: components is defined and 'controlplane_init' in components

- include: controlplane.yml
  when: components is defined and 'controlplane' in components

- include: worker.yml
  when: components is defined and 'worker' in components
