---

- debug: var=k8s.version

- include: tools.yml
  when: components is defined and 'tools' in components

- include: containerd.yml
  when: runtime is defined and runtime == 'containerd'

- include: prepare.yml
  when: components is defined and 'single_node' in components

- include: single_node.yml
  when: components is defined and 'single_node' in components
