#apiVersion: kubeadm.k8s.io/v1beta1
#kind: InitConfiguration
#bootstrapTokens:
#  - groups:
#      - system:bootstrappers:kubeadm:default-node-token
#    token: {{ bootstrap_token.stdout_lines.0 }}
#    ttl: 24h0m0s
#    usages:
#      - signing
#      - authentication
#nodeRegistration:
#  criSocket: {{ k8s.cri_socket }}
#---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
  - "{{ k8s.load_balancer }}"
controlPlaneEndpoint: "{{ k8s.load_balancer }}:6443"
networking:
  podSubnet: "{{ k8s.pod_network }}"
