---

- name: Test
  shell: function join_by { local IFS="$1"; shift; echo "$*"; }; join_by "," $(for IP in $(kubectl --kubeconfig=/etc/kubernetes/admin.conf get nodes --selector=node-role.kubernetes.io/master= -o jsonpath='{.items[*].status.addresses[?(@.type=="InternalIP")].address}'); do echo "https://$IP:2379"; done)
  args:
    executable: /bin/bash
  register: etcd_hosts

- name: Patch
  replace:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    regexp: "--etcd-servers=.+"
    replace: "--etcd-servers={{ etcd_hosts.stdout_lines.0 }}"
  become: yes
  when: 'etcd_hosts is defined and not etcd_hosts.failed'
