---

- name: Check for running control plane
  shell: "systemctl is-active kubelet | grep -v inactive"
  ignore_errors: yes
  register: kubelet_service_not_present

- include: cluster-init.yml
  when: 'kubelet_service_not_present is defined and not kubelet_service_not_present.failed'