---

- name: Check for required variables
  command: "false"
  when: 'k8s.pod_network is undefined or k8s.load_balancer is undefined'

- name: Check for running control plane
  shell: "systemctl is-active kubelet | grep -E '^active$'"
  ignore_errors: yes
  register: kubelet_service_present

- include: cluster-init.yml
  when: 'kubelet_service_present is defined and kubelet_service_present.failed'
