---

- name: Check for required variables
  command: "false"
  when: 'k8s.pod_network is undefined or k8s.load_balancer is undefined'

- name: Check for running control plane
  shell: "systemctl is-active kubelet || true"
  ignore_errors: yes
  become: yes
  register: kubelet_state

- include: cluster-init.yml
  when: 'kubelet_state is defined and not kubelet_state.failed and kubelet_state.stdout_lines | length == 1 and kubelet_state.stdout != "active"'
