---

- name: Check for running control plane
  shell: "netstat -tulpan | grep LISTEN | grep :::6443"
  ignore_errors: yes
  register: port_6443

- include: cluster-init.yml
  when: 'port_6443 is defined and port_6443.failed'