---

- name: Check for required variables
  command: "false"
  when: 'k8s.load_balancer is undefined'

- name: Check for running control plane
  shell: "systemctl is-active kubelet || true"
  ignore_errors: yes
  become: yes
  register: kubelet_state

- include: controller-join.yml
  when: 'first_controller is defined and kubelet_state is defined and not kubelet_state.failed and kubelet_state.stdout_lines | length == 1 and kubelet_state.stdout == "inactive"'
