---

- name: Check for running control plane
  shell: "systemctl is-active kubelet | grep -E '^active$'"
  ignore_errors: yes
  become: yes
  register: kubelet_service_present

- include: controller-join.yml
  when: 'kubelet_service_present is defined and kubelet_service_present.failed'