---

- name: Configure kubelet to use containerd
  patch:
    src: 10-kubeadm.conf.patch
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  become: yes

- name: Add containerd configuration to kubelet
  copy:
    src: 0-containerd.conf
    dest: /etc/systemd/system/kubelet.service.d
    owner: root
    group: root
  become: yes

- name: Reload daemon configuration
  systemd:
    daemon_reload: yes
  become: yes
