---

- name: Install prerequisites
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add Docker apt key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
  become: yes

- name: Pin engine to specified version
  template:
    src: docker-ce
    dest: /etc/apt/preferences.d/
  become: yes

- name: install docker-ce
  apt:
    name: docker-ce
    update_cache: yes
  become: yes

- name: Install daemon configuration
  copy:
    src: daemon.json
    dest: /etc/docker
    owner: root
    group: root
  become: yes

- name: Configure service
  systemd:
    name: docker
    enabled: yes
    state: restarted
