---

- name: Install prerequisites
  apt:
    name: "{{ containerd.prerequisites }}"
    update_cache: yes
  become: yes

- name: Install containerd
  unarchive:
    src: "https://github.com/containerd/containerd/releases/download/v{{ containerd.version }}/containerd-{{ containerd.version }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: yes
  become: yes

- name: Install service configuration
  get_url:
    url: "https://github.com/containerd/containerd/raw/master/containerd.service"
    dest: "/etc/systemd/system/containerd.service"
  become: yes

- name: Create default configuration
  command: containerd config default > /etc/containerd/config.toml

- name: Configure service
  systemd:
    name: containerd
    enabled: yes
    state: started
    daemon_reload: yes
