---

- name: Check if required variables are defined
  command: "false"
  when: 'k8s.load_balancer is undefined'

- name: Check for running control plane
  shell: "systemctl is-active kubelet | grep -E '^active$'"
  ignore_errors: yes
  become: yes
  register: kubelet_service_present

- include: worker-join.yml
  when: 'controller is defined and kubelet_service_present is defined and kubelet_service_present.failed'
