---

- name: Check for running control plane
  shell: "systemctl is-active kubelet | grep -v inactive"
  ignore_errors: yes
  register: kubelet_service_not_present

- include: worker-join.yml
  when: 'kubelet_service_not_present is defined and kubelet_service_not_present.failed'