---

- name: Read join command
  command: "cat cluster/join_command.txt"
  register: join_command
  delegate_to: 127.0.0.1

- name: Join worker
  command: "{{ join_command.stdout_lines.0 }}"
  become: yes
