---

- name: Determine CRI socket
  stat:
    path: /var/run/containerd/containerd.sock
  become: yes
  register: containerd_sock

- debug: var=containerd_sock

- name: Add parameter for CRI socket
  set_fact:
    cri_socket: "--cri-socket /var/run/containerd/containerd.sock"
  when: 'containerd_sock.exists and containerd_sock.issock'

- name: Generate short-lived join token
  command: "kubeadm token create --description='Join for {{ inventory_hostname }}' --ttl=5m"
  become: yes
  delegate_to: "{{ groups['cluster_init'][0] }}"
  register: join_token

- name: Generate hash for CA certificate
  shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"
  become: yes
  delegate_to: "{{ groups['cluster_init'][0] }}"
  register: public_key_hash

- name: Join worker
  shell: "kubeadm join {{ k8s.load_balancer }}:6443 --token {{ join_token.stdout_lines.0 }} --discovery-token-ca-cert-hash sha256:{{ public_key_hash.stdout_lines.0 }} {{ cri_socket }}"
  become: yes
